"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var alumnos_1 = require("./alumnos");
var profesores_1 = require("./profesores");
var escuela_1 = require("./escuela");
var alumno1 = new alumnos_1.alumno('David', 'juarez', 8, true);
var alumno2 = new alumnos_1.alumno('David', 'Jimenez', 0, false);
var lista1 = [alumno1];
var lista2 = [alumno1, alumno2];
alumno2.setNota(6);
var profesorBeto = new profesores_1.profesor('Beto', 'elProfe', 'POO', lista1);
var profesorRaul = new profesores_1.profesor('Raul', 'ElOtroProfe', 'Apis', lista2);
var profesores1 = [profesorBeto, profesorRaul];
var escuela1 = new escuela_1.escuela('Cresta', 'Maipu', profesores1, lista2, 8);
console.log(escuela1);
alumno1.notas();
alumno2.notas();
console.log('-------------------------------------------------');
profesorBeto.listarAlumnos();
console.log("------------------------------------------------");
escuela1.registroAlumnos();
console.log("------------------------------------------------");
escuela1.registroProfesores();
console.log("------------------------------------------------");
escuela1.despedir(1);
escuela1.registroProfesores();
console.log('-------------------------------------------------');
var profeJorge = new profesores_1.profesor('Jorge', 'Feriado', 'SQL', lista2);
escuela1.contratar(profeJorge);
escuela1.registroProfesores();
console.log('-------------------------------------------------');
var alumno3 = new alumnos_1.alumno('sebastian', 'suarez', 7, true);
escuela1.matricular(alumno3);
escuela1.registroAlumnos();
